### ISSUE TITLE
Setup Project from legacy Zygote Cart

### ISSUE THREAD

**Issue by codevelopit** [escaladesports/vt-zygote-cart#1]
Setup project from Legacy Zygote Cart
https://github.com/escaladesports/legacy-zygote-cart

**Comment by rdourney** [comment]
@codevelopit can you add a step-by-step checklist here to the first comment so that we know what tasks need to be completed still?

**Comment by codevelopit** [comment]
@rdourney the cart project is setup and able to run locally on the new cart. 
@vcabieles is working on the current tasks, I'll coordinate with him and add more details to this ticket.

**Comment by rdourney** [comment]
I know @vcabieles is working through understanding the zygote cart but I wanted to see where we are at with @codevelopit discussing further with @vcabieles  and getting tasks/checkboxes made for this ticket.

**Comment by vcabieles** [comment]
@codevelopit already completed this task.
the things i am working on are on ticket:
https://github.com/escaladesports/vt-order-composer/issues/8
https://github.com/escaladesports/victorytailgate.com-gatsby/issues/694
https://github.com/escaladesports/victorytailgate.com-gatsby/issues/617
